### PR TITLE
add 2 options for control color overlay and text color on overlay

### PR DESCRIPTION
**Pull request by sravel**
I found solution to implement fonctions for issus #122

### CODE REVIEW

**Comment by werdeil** [comment]
Hi Sébastien,

I'm glad that you found a way to have the rendering you want but I'm not ok with adding options that are useful only for users that change the code. For me If you use an unpacked version of pibooth to change the pictos you can directly change the code. We already have too many options in the config (see #50)

Without changing the pictos your new option is useless and destroying the work we've made to have an adaptive color.

But this is only my opinion but for me if we want to add such feature we need to also add an easy way to customize the pictos.

**Comment by sravel** [comment]
Yes it's true I hadn't thought that we had to modify the images in the code to change them ...
Do you think of a solution to leave the choice to the user?
I will try to see.
Thank you

**Comment by werdeil** [comment]
To avoid the recolor option, I've pushed a new branch which check if the png image is in grey scale before coloring it. This could be a good start to avoid adding unnecessary option.

**Comment by sravel** [comment]
Thank for the branch, I found other solution to change color on text overlay, just add no text on the translation.cfg and directly add on the new image.
So pull request not mandatory, 
good job !!!

**Pull request closed without merging**
